# AWS Load Balancer Controller Installation Guide
#
# This file provides instructions for installing the AWS Load Balancer Controller
# which enables Kubernetes Ingress resources to create AWS Application Load Balancers
#
# Prerequisites:
# 1. EKS cluster deployed via Terraform
# 2. kubectl configured to access the cluster
# 3. Helm 3 installed

---
# Step 1: Add the EKS Helm repository
# Run: helm repo add eks https://aws.github.io/eks-charts
# Run: helm repo update

---
# Step 2: Create the ServiceAccount with IAM role annotation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_TERRAFORM_OUTPUT  # Get from: terraform output -raw aws_load_balancer_controller_role_arn

---
# Step 3: Install the AWS Load Balancer Controller using Helm
#
# Run the following command (replace values as needed):
#
# helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
#   -n kube-system \
#   --set clusterName=CLUSTER_NAME \  # Get from: terraform output -raw eks_cluster_name
#   --set serviceAccount.create=false \
#   --set serviceAccount.name=aws-load-balancer-controller \
#   --set region=REGION \  # e.g., us-east-1
#   --set vpcId=VPC_ID  # Get from: terraform output -raw vpc_id

---
# Step 4: Verify the installation
# Run: kubectl get deployment -n kube-system aws-load-balancer-controller
# Run: kubectl logs -n kube-system deployment/aws-load-balancer-controller

---
# Alternative: Using a script
# Save this as install-aws-lb-controller.sh and run it:
#
# #!/bin/bash
# set -e
#
# CLUSTER_NAME=$(terraform output -raw eks_cluster_name)
# REGION=$(terraform output -raw aws_region)
# VPC_ID=$(terraform output -raw vpc_id)
# ROLE_ARN=$(terraform output -raw aws_load_balancer_controller_role_arn)
#
# # Create service account
# kubectl apply -f - <<EOF
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: aws-load-balancer-controller
#   namespace: kube-system
#   annotations:
#     eks.amazonaws.com/role-arn: ${ROLE_ARN}
# EOF
#
# # Add helm repo
# helm repo add eks https://aws.github.io/eks-charts
# helm repo update
#
# # Install controller
# helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
#   -n kube-system \
#   --set clusterName=${CLUSTER_NAME} \
#   --set serviceAccount.create=false \
#   --set serviceAccount.name=aws-load-balancer-controller \
#   --set region=${REGION} \
#   --set vpcId=${VPC_ID}
#
# echo "AWS Load Balancer Controller installed successfully!"
# kubectl get deployment -n kube-system aws-load-balancer-controller
